### ISSUE TITLE
Sapper + Adren/Energ/Frenzy Interaction doesn't work.

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer#15]
Breaking a spawner with Sapper + Adrenaline pickaxe doesn't give you the Adrenaline buff even though the Wiki states that the interaction should work like that.

**Comment by pearuhdox** [comment]
This has been fixed by changing the interaction. In 1.20.2, Adrenaline, Energetic, and Frenzy have been changed to count breaking a spawner as a kill.
