### ISSUE TITLE
the combination of wavedash+ricochet is not working

### ISSUE THREAD

**Issue by swzedgdgnjusbh** [pearuhdox/Cartographer#17]

**Comment by pearuhdox** [comment]
Found an issue that was causing Ricochet to not work as intended. Fixing this, Wavedash Ricochet interaction is now the trident will hit other enemies, but the player will only teleport to the first one hit. For now, this is "works as intended" as teleport bouncing to different mobs would likely be very disorienting. Might change later if design improves with it, but Ricochet is fixed for 1.20.2
