### ISSUE TITLE
Cavespiders deals 0 damage/fails to hit player while having Death effects.

### ISSUE THREAD

**Issue by ConeOfSnow** [pearuhdox/Cartographer#32]
Tested with brutal blood and corpsecrawler

Cavespiders completely fail to hit the player for any damage even with a axe if they have Brutal blood and Corpsecrawler (other effects may be affected too) 

Recreation command: /give @p spawner{display:{Name:'{"text":"DEATH PIT MOB"}'},BlockEntityTag:{Delay:1,MinSpawnDelay:600,MaxSpawnDelay:800,MaxNearbyEntities:3,RequiredPlayerRange:10,SpawnData:{custom_spawn_rules:{sky_light_limit:{min_inclusive:0,max_inclusive:15},block_light_limit:{min_inclusive:0,max_inclusive:15}},entity:{id:"minecraft:cave_spider",Tags:["ca.has_death","ca.blood"],HandItems:[{id:"minecraft:wooden_axe",Count:1b},{}]}}}} 1

**Comment by pearuhdox** [comment]
Unfortunately this is a bug caused by Mojang I cannot solve. You can attach a mob above the spider to fix its AI and use the soul_chain tag to make them die together.
