### ISSUE TITLE
i cannot slick up men (oil application bug)

### ISSUE THREAD

**Issue by RockNRui** [pearuhdox/Cartographer#40]
Hitting a mob wearing the following pants for some reason applies bleeding alongside the intended Oiled effect:
`/give @s minecraft:chainmail_leggings{HasOverride:1b,OverrideMelee:1b,apply_status:[{id:"oiled",amplifier:4b,duration:200}]}`

When just using a sword, no such problem happens and just Oiled is applied.
`/give @s diamond_sword{apply_status:[{id:"oiled",duration:100,amplifier:4b}]}`

**Comment by pearuhdox** [comment]
Issue resolved in most recent commit.
