### ISSUE TITLE
Shulker bullets fired using the ca.shoot_shulker_bullet tag still inflict Levitation on mobs

### ISSUE THREAD

**Issue by Zungrysoft** [pearuhdox/Cartographer#8]
Shulker bullets fired using the ca.shoot_shulker_bullet tag are not supposed to inflict Levitation, but they still inflict Levitation on other mobs. They don't inflict Levitation on players, as intended.

I used this command to spawn the mobs:

```setblock ~ ~ ~ spawner{MaxNearbyEntities: 3s, RequiredPlayerRange: 16s, SpawnCount: 100s, MinSpawnDelay: 200s, MaxSpawnDelay: 800s, Delay: 1s, SpawnRange: 3s, SpawnPotentials: [{Entity: {id:"minecraft:skeleton",CustomName:'[{"text":"Voodoo Child"}]',Health:10,Attributes:[{Name:"generic.max_health",Base:20F},{Name:"generic.movement_speed",Base:0.2f}],HandItems:[{id:bow,Count:1,tag:{Enchantments:[{id:"minecraft:power",lvl:1}]}}],ArmorItems:[{id:leather_boots,tag:{display:{color:1382942}},Count:1},{id:leather_leggings,tag:{display:{color:1382942}},Count:1},{id:netherite_chestplate,Count:1},{id:player_head,tag:{SkullOwner:{Id:[I;1266830179,-319667587,-1458070666,-685980425],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODZjNDQ3NzYzYTFmNzljNDVjYWFlMjUwYzY2MTk1YjUxM2ZmOGY1NjY0ZDRhODExM2I3MTBkYWYzYzE4ZSJ9fX0="}]}}},Count:1}],HandDropChances:[0F,0F],ArmorDropChances:[0F,0F,0F,0F],DeathLootTable:"",Tags:["ca.shoot_shulker_bullet"]},Weight:1}]}```

**Comment by pearuhdox** [comment]
Unfortunately, this isn't fixable without causing major performance issues to the rest of Cartographer, given how Cartographer uses EHID to clear and assign effects efficiently in the advancement tick. Since entity on entity hits don't trigger advancements, this isn't doable without major rewrites and performance complications.
