### ISSUE TITLE
Colossus of Pride + Colossus of Greed not instantly aggroing.

### ISSUE THREAD

**Issue by SlimeKing77777** [pearuhdox/Cartographer#9]
Whenever a Colossus of Pride or Greed is spawned, it doesn't instantly aggro to the player. Pride also attacks other mobs due to it being an iron golem.

**Comment by pearuhdox** [comment]
UniversalAnger gamerule must be true in order for golems to aggro on players with anger time (as well as any neutral mob). Pride will attack other mobs and that is classified as won't fix because it would require setting every mob to a team, which is not a viable option for Cartographer.
